### ISSUE TITLE
Investigate how to use the HW barrier of Snitch

### ISSUE THREAD

**Issue by rgantonio** [KULeuven-MICAS/snitch_cluster#18]
Gianna told us that Snitch has interrupt mechanisms. The code seems to have so but we need to identify how to handle those. Investigate how to use the interrupts of Snitch and modify tests to use those.

**Comment by JosseVanDelm** [comment]
Happy to help out here

**Comment by rgantonio** [comment]
This was investigated internally. For documentation purposes, we can find it on a Notion page [here](https://danknight.notion.site/Snitch-Hardware-Barrier-e46e8b2072a5407b8ed00f318c0a69e6?pvs=4).

The concept is simple, basically when `snitch_hw_barrier()` function is called, it does a load operation but that load operation stalls until all cores have reached that "load" operation.
