### ISSUE TITLE
Add test data generation

### ISSUE THREAD

**Issue by JosseVanDelm** [KULeuven-MICAS/snitch_cluster#29]
See #27 .
We would like to generate the data automatically.
Examples of this are also available in https://github.com/kuleuven-micas/snax-mlir

**Comment by JosseVanDelm** [comment]
@rgantonio have a look here:
https://github.com/KULeuven-MICAS/snax-mlir/blob/main/kernels/simple_mult/gendata.py

**Comment by rgantonio** [comment]
@JosseVanDelm yup I saw! Will add one later!

**Comment by JosseVanDelm** [comment]
Closing since we now have #33 and #36
