### ISSUE TITLE
Investigating the TCDM costs

### ISSUE THREAD

**Issue by guilherme-paim** [KULeuven-MICAS/snitch_cluster#30]
I bring this up because we need to start to understand the breakdown cost and the scalability of our cluster.

1) In the current TCDM implementation, each port of the accelerator can access all the different banks in a non-contiguous way. 
If the TCDM is an overhead to the scalability, probably it is, we can agglomerate N ports to the accelerator.

2) We need to see the cost of implementing parallel and independent read and write via TCDM.

How we will do it? In a different repo?

**Comment by rgantonio** [comment]
We already have a separate branch per tests. I will clean it up with the latest updates from the main. Remember our "branch" workbench? 😄 We also really need to think about the best way to run multiple experiments without breaking the main branch and still having a setup for the RTL people.

Making another repo might be cumbersome... I think? Depends 😃

**Comment by rgantonio** [comment]
We have initial results for how the TCDM scales in terms of the number of input ports (the cores or the requesters) and the number of output ports (the number of memory banks).

**Comment by rgantonio** [comment]
For documentation purposes see more information in this Notion [link](https://danknight.notion.site/Snitch-TCDM-Study-559bc1e7b2b24de9be3c59428b76791f?pvs=4).
