### ISSUE TITLE
illegal instruction on tiled mult example

### ISSUE THREAD

**Issue by JosseVanDelm** [KULeuven-MICAS/snitch_cluster#37]
Hi 

I secretly added some bugs (:shrug:) in #33 and #36 for some sizes of vec_len and tile_size.

This sometimes results in different incarnations of:
```
[fesvr] Wrote 36 bytes of bootrom to 0x1000
[fesvr] Wrote entry point 0x80000000 to bootloader slot 0x1020
[fesvr] Wrote 56 bytes of bootdata to 0x1024
[Tracer] Logging Hart          0 to logs/trace_hart_00000000.dasm
[Tracer] Logging Hart          1 to logs/trace_hart_00000001.dasm
[Illegal Instruction Core 1] PC: 0000000018ce Data: 00000000
```
Sometimes multiple `[Illegal Instruction Core 1]`'s appear.
The PC is typically set to a different value each time...

**Comment by rgantonio** [comment]
This problem is caused by a lock that happens on the MAC engine because the timing of the control signals causes a deadlock.

PE #39  fixes this :) (hopefully)
