### ISSUE TITLE
Synchronizing this repo with the latest Snitch cluster core.

### ISSUE THREAD

**Issue by rgantonio** [KULeuven-MICAS/snitch_cluster#43]
There are several commits in the original Snitch cluster repo that we need to add to ours. We cannot merge because there are several conflicts, but they have very nice updates. I think it's important that we do this soon.

**Comment by JosseVanDelm** [comment]
@rgantonio I agree.

---------
:warning: **This is something that most likely requires a force push to our own _main_ branch. Which is a bit dangerous, so we should align who will do this, when, ...**

--------

Can we make a list here of things we need/want/could use?

I would first try to finish off some of our own milestones before proceeding with this, can we list these as well? I think we should try to help @xiaoling-yi to get her stuff merged and then we can do the rebase maybe?

@jorendumoulin and me are very excited about this draft PR: https://github.com/pulp-platform/snitch_cluster/pull/61
LLVM 15 introduces opaque pointer types, which would give us way nicer IR, and less hacks to get stuff working end-to-end.

**Comment by rgantonio** [comment]
@JosseVanDelm @jorendumoulin @guilherme-paim @xiaoling-yi 

LET'S MAKE THIS FIRST PRIORITY NEXT WEEK! MONDAY? 😄 

I feel like we need this ASAP before it's too late. Haha. I am proposing we reserve a room and do live debugging with everyone. There are indeed FREAKISHLY several new commits.

**Comment by JosseVanDelm** [comment]
@rgantonio it's a bit scary indeed, but at the same time most upstream commits do not seem to interfere in any way with our work, so rebasing on top of those won't be too difficult I think.
Also, regarding "it's too late", we'll probably have to do this several more times, so... yeah ...

**Comment by rgantonio** [comment]
@JosseVanDelm let's do this Tuesday isntead? haha I have a different task this Monday :(

**Comment by rgantonio** [comment]
This has been accomplished last Dec 20, 2023!
