### ISSUE TITLE
Question about address calculation in snax-gemm lib

### ISSUE THREAD

**Issue by jorendumoulin** [KULeuven-MICAS/snitch_cluster#54]
https://github.com/KULeuven-MICAS/snitch_cluster/blob/13464ee7897e71f04e75213f3f9094ed75c3aa17/target/snitch_cluster/sw/snax/gemm/src/snax-gemm-lib.c#L102-L109

In the address calculation for copying data from L3 to L1, why do we divide by `sizeof(int8_t)`. Should we not multiply with `sizeof(int8_t)`? I guess because `sizeof(int8_t)` is 1 in this case it does not result in an error.

**Comment by xiaoling-yi** [comment]
No actually not. The strides are the absolute address (8bit = 1byte =1 address increment). But the pointer operation, for example, ptr_a + x, is actually increasing the address to ptr_a + sizeof(each element of the vector that ptr_a point to)*x. So to get the absolute address using stride and pointer opretaion, we need to do ptr_a + strides/sizeof(each element of the vector that ptr_a point to).

**Comment by jorendumoulin** [comment]
Ah, I see! I understand why it is necessary for the calculation of `addr_a`. However, for the calculation of `addr_A`, no strides are used, only variables `meshRow` and `tileSize`. Do we also need the division by `sizeof(int8_t)` here?

**Comment by xiaoling-yi** [comment]
See here: https://github.com/KULeuven-MICAS/snitch_cluster/pull/62
