### ISSUE TITLE
What happens to signals that are tied to zero in Synthesis?

### ISSUE THREAD

**Issue by rgantonio** [KULeuven-MICAS/snitch_cluster#8]
This may differ per synthesis tool but when we start synthesizing things for the technology we are using, we need to find out how the tools treat tied to zero signals.

As far as I know, tied to zero signals are either (1) literally tied to zero or they (2) melt in the synthesized version.

**Comment by guilherme-paim** [comment]
Modern synthesis tools (Genus) have a 'constant signals propagation' pass, in which all signals constantly assigned to zero (or one) automatically simplify their following logic circuits.

**Comment by JosseVanDelm** [comment]
@rgantonio can we close this?
